name: Main Deployment workflow
on:
  push:
    branches:
      - main
      - develop
      - "feature/*"

permissions:
  id-token: write
  contents: read

jobs:
  deploy-dev:
    name: Deploy to Dev
    uses: ./.github/workflows/deploy-services.yml
    with:
      environment: dev
      aws_account_id: "474668415523"

  deploy-prod:
    name: Deploy to Prod
    needs: deploy-dev
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    uses: ./.github/workflows/deploy-services.yml
    with:
      environment: prod
      aws_account_id: "054037129431"
