name: Main Workflow

on:
  push:
    branches:
      - main
      - develop
      - "feature/*"

permissions:
  id-token: write
  contents: read

jobs:
  deploy-dev:
    name: Deploy to Dev
    uses: ./.github/workflows/services-deploy.yml
    with:
      environment: dev
      aws_account_id: "474668415523"
      lambda_functions: >-
        [
          {"name": "get-student-data", "directory": "lambdas/workers/GetStudentData"},
          {"name": "get-student-courses", "directory": "lambdas/workers/GetStudentCourses"},
          {"name": "get-program-details", "directory": "lambdas/workers/GetProgramDetails"},
          {"name": "hello_world", "directory": "lambdas/HelloWorld"},
          {"name": "student-query-intake", "directory": "lambdas/orchestrators/QueryIntake"},
          {"name": "student-query-llm-analyzer", "directory": "lambdas/orchestrators/LLMQueryAnalyzer"},
          {"name": "student-query-worker-dispatcher", "directory": "lambdas/orchestrators/WorkerDispatcher"},
          {"name": "student-query-response-aggregator", "directory": "lambdas/orchestrators/ResponseAggregator"},
          {"name": "student-query-answer-generator", "directory": "lambdas/orchestrators/AnswerGenerator"},
          {"name": "student-query-status", "directory": "lambdas/orchestrators/QueryStatus"},
          {"name": "student-query-user-data-generator", "directory": "lambdas/orchestrators/UserDataGenerator"}
        ]

  deploy-prod:
    name: Deploy to Prod
    needs: deploy-dev
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    uses: ./.github/workflows/services-deploy.yml
    with:
      environment: prod
      aws_account_id: "054037129431"
      lambda_functions: >-
        [
          {"name": "get-program-details", "directory": "lambda/GetProgramDetails"},
          {"name": "hello_world", "directory": "lambda/HelloWorld"}
        ]
