name: Services Deploy (Reusable)

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      aws_account_id:
        required: true
        type: string
      lambda_functions:
        required: false
        type: string
        description: 'JSON array of Lambda functions to deploy, e.g. [{"name": "db-migration-runner", "directory": "lambda", "runtime": "nodejs"}]'
        default: "[]"

permissions:
  id-token: write
  contents: read

jobs:
  deploy-lambda-functions:
    name: Deploy Lambda Functions to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    env:
      AWS_REGION: "eu-west-2"
    strategy:
      fail-fast: false
      matrix:
        function: ${{ fromJSON(inputs.lambda_functions) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/GithubActionsLambdaDeployRole
          role-session-name: GitHubLambdaDeploySession
          aws-region: ${{ env.AWS_REGION}}

      - name: Detect function runtime
        id: detect-runtime
        run: |
          cd ${{ matrix.function.directory }}
          if [ -d "python" ]; then
            echo "runtime=python" >> $GITHUB_OUTPUT
          elif [ -f "package.json" ]; then
            echo "runtime=nodejs" >> $GITHUB_OUTPUT
          else
            echo "No identifiable runtime found. Defaulting to nodejs."
            echo "runtime=nodejs" >> $GITHUB_OUTPUT
          fi

      # Setup and build Node.js lambdas
      - name: Install Node.js
        if: steps.detect-runtime.outputs.runtime == 'nodejs'
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Build Node.js Lambda package - ${{ matrix.function.name }}
        if: steps.detect-runtime.outputs.runtime == 'nodejs'
        run: |
          cd ${{ matrix.function.directory }}
          npm install --production
          zip -r ../${{ matrix.function.name }}.zip .

      # Setup and build Python lambdas
      - name: Install Python
        if: steps.detect-runtime.outputs.runtime == 'python'
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Build Python Lambda package - ${{ matrix.function.name }}
        if: steps.detect-runtime.outputs.runtime == 'python'
        run: |
          cd ${{ matrix.function.directory }}
          mkdir -p ./package
          # Install dependencies
          pip install -r python/requirements.txt -t ./package
          # Copy Lambda function code
          cp python/lambda_function.py ./package/
          # Copy agent directories if they exist
          if [ -d "agent" ]; then
            mkdir -p ./package/agent
            cp -r agent/* ./package/agent/
          fi
          cd ./package
          zip -r ../../${{ matrix.function.name }}.zip .

      - name: Upload Lambda package to S3 - ${{ matrix.function.name }}
        run: |
          aws s3 cp $(dirname ${{ matrix.function.directory }})/${{ matrix.function.name }}.zip s3://lambda-deployments-${{ inputs.aws_account_id }}/functions/${{ matrix.function.name }}.zip

      - name: Update Lambda code from S3 - ${{ matrix.function.name }}
        run: |
          aws lambda update-function-code \
            --function-name ${{ matrix.function.name }} \
            --s3-bucket lambda-deployments-${{ inputs.aws_account_id }} \
            --s3-key functions/${{ matrix.function.name }}.zip
